version: "1"
pipelines:
  - name: product-api-documentation-deployment:1.0.0
    description: Compiles and deploys the documentation of the Schier Product API to
      Firebase.
    env:
      static:
        - DEBIAN_FRONTEND=noninteractive
        - TERM=linux
        - CLI_INSTALL_LOCATION=/tmp/required_cli_tools
        - DOCKER_REGISTRY=ghcr.io
        - GITHUB_ORG=schierproducts
        - GITHUB_REPO=schier-api-documentation
      secrets:
        - GITHUB_TOKEN
        - FIREBASE_TOKEN
    events:
      - "github:schierproducts/schier-api-documentation:pull_request.merged" 
      - "github:schierproducts/schier-api-documentation:create.tag" 
    jobs:
      - name: deploy-product-api-documentation
        description: Compile and deploy the documentation to Firebase production environment.
        packages:
          - unzip
          - git
          - wget
          - tree
        steps:
          #INSTALL TOOLS
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          - nvm install 14 && nvm use 14
          # NPM / YARN
          - npm -v
          - npm install -g yarn firebase-tools
          - yarn --version
          - git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/$GITHUB_ORG/$GITHUB_REPO #Remote only
          - cd $GITHUB_REPO
          - yarn && yarn build
          - firebase use schier-api-documentation --token $FIREBASE_TOKEN
          - firebase deploy --non-interactive --token $FIREBASE_TOKEN
services:
  - name: product-api-documentation-preview:1.0.0
    description: Preview the Schier Products Product API documentation.
    run: npm run dev
    port: [ '8080:8080' ]
    trigger:
     - build
     - publish
     - start
