parameters:
  - name: ProductTypeKey
    description: The unique identifier of the product type to be retrieved.
    in: path
    required: true
    schema:
      $ref: '#/components/schemas/ProductTypeKey'
get:
  summary: Retrieve a list of product types.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: "../schema/product-type.yaml"
          example:
            object: 'product-type'
            url: '/product-types/sampling_port'
            name: 'Sampling Port'
            key: 'sampling_port'
            active: true
            created: '11/24/2020'
            last_updated: null
            types: []
    '401':
      $ref: '../errors/401.yaml'
    '403':
      $ref: '../errors/403.yaml'
    '404':
      description: 'The product type could not be found based on the provided key.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'This product type could not be found.'
    '500':
      $ref: '../errors/500.yaml'