get:
  summary: Retrieve a list of product types.
  responses:
    '200':
      description: OK
      headers:
        date:
          schema:
            type: string
          description: A timestamp of when the request was issued.
        server:
          schema:
            type: string
          description: The type of server that responded with the request.
        vary:
          schema:
            type: string
          description: The type of permissions that are being used.
        'x-powered-by':
          schema:
            type: string
          description: The programmoing language and it's version that is being used to respond
        'x-ratelimit-limit':
          schema:
            type: number
          description: The number of requests that are allowed within a certain time period before the rate limiting rules are enforced.
        'x-ratelimit-remaining':
          schema:
            type: number
          description: The number of requests that are remaining before the rate limiting rules are enforced.
        'cache-control':
          schema:
            type: string
          description: The type of caching that is used.
        'access-control-allow-origin':
          schema:
            type: string
          description: The allowed CORS settings.
        'content-type':
          schema:
            type: string
          description: The allowed/expected content type.
        'set-cookie':
          required: false
          schema:
            type: string
          description: The cookie that is set by the applications load balancer for performance.
        'transfer-encoding':
          schema:
            type: string
          description: Encoding settings.
      content:
        schema:
          type: object
          properties:
            object:
              type: string
              default: 'list'
            url:
              type: string
              description: 'The url that can be used to retrieve this product type list.'
              example: '/product-types'
            data:
              type: array
              description: 'A list of available product types that are available in the API'
              items:
                $ref: '#/components/schemas/ProductType'
          example:
            type: 'list'
            url: '/product-types'
            data:
              - object: 'product-type'
                url: '/product-types/hydromechanical_grease_interceptor'
                name: 'Hydromechanical Grease Interceptor'
                key: 'hydromechanical_grease_interceptor'
                active: true
                created: '11/24/2020'
                last_updated: null
                parent: null
                types: [ ]
              - object: 'product-type'
                url: '/product-types/gravity_grease_interceptor'
                name: 'Gravity Grease Interceptor'
                key: 'gravity_grease_interceptor'
                active: true
                created: '11/24/2020'
                last_updated: null
                parent: null
                types: [ ]
              - object: 'product-type'
                url: '/product-types/accessory'
                name: 'Accessory'
                key: 'accessory'
                active: true
                created: '11/24/2020'
                last_updated: null
                parent: null
                types:
                  - object: 'product-type'
                    url: '/product-types/riser'
                    name: 'Riser'
                    key: 'riser'
                    active: true
                    created: '11/24/2020'
                    last_updated: null
                  - object: 'product-type'
                    url: '/product-types/pumpout_port'
                    name: 'Pumpout Port'
                    key: 'pumpout_port'
                    active: true
                    created: '11/24/2020'
                    last_updated: null
        example:
          object: 'product-type'
          url: '/product-types/accessory'
          name: 'Accessory'
          key: 'accessory'
          active: true
          created: '11/24/2020'
          last_updated: null
          parent: null
          types:
            - object: 'product-type'
              url: '/product-types/riser'
              name: 'Riser'
              key: 'riser'
              active: true
              created: '11/24/2020'
              last_updated: null
            - object: 'product-type'
              url: '/product-types/pumpout_port'
              name: 'Pumpout Port'
              key: 'pumpout_port'
              active: true
              created: '11/24/2020'
              last_updated: null
    '401':
      $ref: '../errors/401.yaml'
    '403':
      $ref: '../errors/403.yaml'
    '500':
      $ref: '../errors/500.yaml'