parameters:
  - name: ModelNumber
    description: The unique identifier of the product to be retrieved.
    in: path
    required: true
    schema:
      $ref: '#/components/schemas/ModelNumber'
get:
  summary: Retrieve a list of products that belong to the provided product type.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
          examples:
            GB1:
              value:
                $ref: '../examples/gb1.yaml'
            'GB-250-B':
              value:
                $ref: '../examples/gb-250-b.yaml'
      headers:
        date:
          schema:
            type: string
          description: A timestamp of when the request was issued.
        server:
          schema:
            type: string
          description: The type of server that responded with the request.
        vary:
          schema:
            type: string
          description: The type of permissions that are being used.
        'x-powered-by':
          schema:
            type: string
          description: The programmoing language and it's version that is being used to respond
        'x-ratelimit-limit':
          schema:
            type: number
          description: The number of requests that are allowed within a certain time period before the rate limiting rules are enforced.
        'x-ratelimit-remaining':
          schema:
            type: number
          description: The number of requests that are remaining before the rate limiting rules are enforced.
        'cache-control':
          schema:
            type: string
          description: The type of caching that is used.
        'access-control-allow-origin':
          schema:
            type: string
          description: The allowed CORS settings.
        'content-type':
          schema:
            type: string
          description: The allowed/expected content type.
        'set-cookie':
          required: false
          schema:
            type: string
          description: The cookie that is set by the applications load balancer for performance.
        'transfer-encoding':
          schema:
            type: string
          description: Encoding settings.
    '401':
      $ref: '../errors/401.yaml'
    '403':
      $ref: '../errors/403.yaml'
    '404':
      description: 'The product with the provided model number could not be found.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: 'The product with the model number "8461684521" could not be found.'
    '500':
      $ref: '../errors/500.yaml'