type: object
description: A specific description of a product that is offered by Schier to be sold via eCommerce or wholesale.
properties:
  object:
    type: string
    default: 'product'
  url:
    type: string
    description: 'The url that can be used to retrieve this product type.'
    example: '/products/4080-031-01'
  id:
    type: number
    description: 'The internal, unique identifier for this product. (For Schier purposes only.)'
  name:
    type: string
    description: 'The name of the product.'
    example: 'GB-1000'
  short_name:
    type: string
    description: 'A shorter/redacted version of the product name. In most cases, it will be the same as the product name.'
    example: 'GB-1000'
  created:
    type: string
    description: 'The date of when the product was created.'
    example: '11/24/2020'
  updated:
    type: string
    nullable: true
    description: 'If available, the date of when the product was updated.'
    example: '11/24/2020'
  types:
    $ref: "#/components/schemas/Types"
  part_number:
    type: string
    description: 'The unique part number that is assigned to this product that also indicates the configuration of input/output fittings and the type of cover fitted to the product.'
    example: '4080-031-01'
  base_model:
    type: object
    properties:
      is_base_model:
        type: boolean
        default: false
        description: If the product that is returned is the base model of the product, this value will be `true`. A base product is identified as the default product that appears on the Schier website in most cases.
      base_part_number:
        type: string
        nullable: true
        default: 'null'
        description: 'If the `base_model_property` is `false`, the part number to the base model of this current product will be printed.'
  store_id:
    type: string
    description: "The eCommerce provider for the Schier website requires that each product configuration (or variant) has a unique identifier. This identifier is used to add the product to shopping carts. **NOTE: This is different that the product id.**"
  shipping_group:
    type: string
    description: 'The shipping rule group that this product belongs to. This group is dictated by the Schier eCommerce store to provide specific pricing and terms to each shipment.'
  active:
    type: boolean
    description: 'Indication if the product is a "published" state and is available for sale.'
  visible_on_store:
    type: boolean
    description: 'Indication if the product should be shown on the website for sale in the eCommerce channel.'
  description:
    type: string
    description: 'A description of the product and its uses.'
  short_description:
    type: string
    nullable: true
    description: 'In the event that product description is long in length, a shorter summary of the product can be provided.'
  market_specific_description:
    type: string
    nullable: true
    description: 'In certain cases, specific descriptions need to be provided for products that solve a need for a market or jurisdiction.'
  website_url:
    type: string
    description: The public-facing url that can be followed to view this product on the Schier website.
  images:
    $ref: "#/components/schemas/ProductImages"
  processing:
    type: object
    properties:
      lead_time:
        type: number
        description: The number of business days required to build the product upon processing.
      threshold:
        type: number
        description: The number of units that can be purchased at once that can be applied to the provided lead time. Any number of units purchased over the provided number will yield a TBD lead time.
  price:
    $ref: "#/components/schemas/Price"
  installation_options:
    type: object
    properties:
      object:
        type: string
        default: installation-options
      location:
        type: object
        properties:
          object:
            type: string
            default: installation-options-location
          indoors:
            type: boolean
            description: If the product can be installed indoors.
          outdoors:
            type: boolean
            description: If the product can be installed outdoors.
          above_grade:
            type: boolean
            description: If the product can be installed above ground (not buried).
          below_grade:
            type: boolean
            description: If the product can be installed below ground (buried, suspended).
          other:
            type: boolean
            description: If the product can be installed in any other locations other than the previously specified.
      location_as_text:
        type: string
        description: A human-friendly version of the boolean flags of the various installation location properties for this product.
      traffic_area:
        type: boolean
        description: If the product can be installed below-ground and in a traffic area.
  ratings:
    type: array
    description: A list of compatible flow rates, efficiency and associated grease capacity combinations for this product.
    items:
      $ref: "#/components/schemas/ProductRating"
  solids_capacity:
    $ref: "#/components/schemas/DimensionSet"
  liquid_capacity:
    $ref: "#/components/schemas/DimensionSet"
  base_dimensions:
    type: object
    description: The dimensions of the product when it is installed/unpackaged.
    properties:
      object:
        type: string
        default: dimension-set
      standard:
        type: object
        description: The measurements of the product using standard units of measurement.
        properties:
          object:
            type: string
            default: dimensions
          length:
            $ref: "#/components/schemas/Measurement"
          width:
            $ref: "#/components/schemas/Measurement"
          height:
            $ref: "#/components/schemas/Measurement"
          weight:
            $ref: "#/components/schemas/Measurement"
      metric:
        type: object
        description: The measurements of the product using metric units of measurement.
        properties:
          object:
            type: string
            default: dimensions
          length:
            $ref: "#/components/schemas/Measurement"
          width:
            $ref: "#/components/schemas/Measurement"
          height:
            $ref: "#/components/schemas/Measurement"
          weight:
            $ref: "#/components/schemas/Measurement"
  shipping_dimensions:
    type: object
    description: The dimensions of the product when it is packaged for shipping in isolation. This will include the pallet if required for shipping.
    properties:
      object:
        type: string
        default: dimension-set
      standard:
        type: object
        description: The measurements of the product using standard units of measurement.
        properties:
          object:
            type: string
            default: dimensions
          length:
            $ref: "#/components/schemas/Measurement"
          width:
            $ref: "#/components/schemas/Measurement"
          height:
            $ref: "#/components/schemas/Measurement"
          weight:
            $ref: "#/components/schemas/Measurement"
      metric:
        type: object
        description: The measurements of the product using metric units of measurement.
        properties:
          object:
            type: string
            default: dimensions
          length:
            $ref: "#/components/schemas/Measurement"
          width:
            $ref: "#/components/schemas/Measurement"
          height:
            $ref: "#/components/schemas/Measurement"
          weight:
            $ref: "#/components/schemas/Measurement"
  manway_access_ports:
    type: number
    nullable: true
    description: The number of manways that the product has. This value is primarily used to indicate the number covers are needed.
  units_in_series:
    type: array
    description: The available number of units that can be "chained" together to create an interceptor system. The number of units could potentially change depending on the jurisdiction requirements.
    nullable: true
    items:
      type: object
      properties:
        object:
          type: string
          default: units-in-series
        number:
          type: number
          description: The number of units of the described interceptor
  related_products:
    type: object
    description: A list of products that can be described as "alternates" for the requested product These alternates are normally modified a specific way to conform to a jurisdicition's specification or requirements.
    properties:
      object:
        type: string
        default: list
      data:
        type: array
        default: []
        items:
          $ref: "#/components/schemas/RelatedProduct"
  accessories:
    type: object
    description: The compatible accessories that can be fitted to this product.
    properties:
      object:
        type: string
        default: list
      data:
        type: array
        default: []
        items:
          $ref: "#/components/schemas/Accessory"
  alternate_accessories:
    type: object
    description: In isolated instances, certain accessories can be "inter-changable" based on the installation specification. These accessories will be listed here.
    properties:
      object:
        type: string
        default: list
      data:
        type: array
        default: []
        items:
          $ref: "#/components/schemas/Accessory"
  options:
    type: object
    description: A list of options that individualize this product and also provide the combinations dictated by the associated model numbers.
    properties:
      object:
        type: string
        default: list
      data:
        type: array
        default: []
        items:
          $ref: "#/components/schemas/ProductOption"

  certifications:
    type: array
    description: Any provided certifications provided by a governing body or any Schier-produced test reports.
    default: []
    items:
      $ref: "#/components/schemas/ProductCertification"
  installation_guide:
    type: object
    description: Available installation guides based on file format and translation.
    properties:
      object:
        type: string
        default: document-library
      pdf:
        type: string
        nullable: true
        description: The installation guide in a PDF format.
      pdf_french:
        type: string
        nullable: true
        description: The installation guide in a PDF format, translated in French.
      pdf_spanish:
        type: string
        nullable: true
        description: The installation guide in a PDF format, translated in Spanish.
      dwg:
        type: string
        nullable: true
        description: The installation guide in a DWG vector format.
  revit:
    type: string
    nullable: true
    description: A link to the requested product's documets in a REVIT format. These files are usually delivered in a ZIP format.
  owners_manual:
    type: string
    nullable: true
    description: A link to the requested product's owners manual.
  csi_masterspec:
    type: string
    nullable: true
    description: A link to the Schier product masterspec document.















