type: object
description: "An attributable characteristic that can be applied to a product option. Available options are:\n\n- inlet\n- outlet"
properties:
  connection_type:
    type: string
    enum:
      - outlet
      - inlet
    example: inlet
  diameter:
    type: string
    description: "The width of the connection in inches. Available options are:\n\n- 2\"\n- 3\"\n- 4\"\n- 6\"\n"
    enum:
      - 2"
      - 3"
      - 4"
      - 6"
    example: 6"
  thread_type:
    type: string
    description: "The type of thread (if any) that the connection exhibits. Available options are:\n\n- Female Thread (FPT)\n- Male Thread (MPT)\n- Plain"
    enum:
      - Female Thread (FPT)
      - Male Thread (MPT)
      - Plain
    example: Female Thread (FPT)
  connection_feature:
    type: string
    nullable: true
    description: Any additional, unique features that this attribute may have.
    enum:
      - None
      - Fixed
    example: Fixed
  has_pumpout_ports:
    type: boolean
    default: false
    description: If this attribute contains pumpout ports that can be used pumpout the interceptor.
  object:
    type: string
    default: product-option-attribute