type: object
properties:
  object:
    type: string
    default: rating
  flow_rate:
    $ref: "#/components/schemas/DimensionSet"
  grease_capacity:
    type: object
    properties:
      object:
        type: string
        default: grease-capacity-measurement
      weight:
        $ref: "#/components/schemas/DimensionSet"
      volume:
        $ref: "#/components/schemas/DimensionSet"
  label:
    type: string
    nullable: true
    description: An optional lable that can be applied to further explain the use/implementation of this rating.
  rating_id:
    type: integer
    description: 'The internal, unique identifier for this product rating. (For Schier purposes only.)'
  order:
    type: integer
    description: The order in which these ratings should be shown (based on Schier ordering rules).
  is_99_percent_efficient:
    type: boolean
    description: If the rating has been classified as 99% efficient. This is primarily used for the Miami DERM jurisdiction/market.
    default: false