type: object
description: A customizable connection or cover that individualizes a product. Unique combinations of these options dictate the associated model numbers.
properties:
  id:
    type: integer
    description: 'The internal, unique identifier for this option. (For Schier purposes only.)'
  name:
    type: string
    description: The name of the option.
    example: '6" Plain Inlet/Outlet'
  option_type:
    type: string
    enum:
      - 'Cover'
      - 'Outlet Configuration'
      - 'Inlet/Outlet'
    description: The type of option that defines this product.
    example: 'Cover'
  desription:
    type: string
    nullable: true
    description: A brief explanation that provides context of what makes this option unique.
  store_id:
    type: integer
    nullable: true
    description: 'The eCommerce provider for the Schier website occasionally requires that each product product has a unique identifier. This identifier is used to add the product to shopping carts. **NOTE: This is different than the option id.**'
  attributes:
    type: array
    default: []
    description: A list of traits that are specific to this option; *ie the diameter and material of a connection.*
    items:
      $ref: "#/components/schemas/ProductOptionAttribute"
  object:
    type: string
    default: product-option