type: object
properties:
  object:
    type: string
    default: 'list'
  url:
    type: string
    description: 'The url that can be used to retrieve this product type list.'
    example: '/product-types'
  data:
    type: array
    description: 'A list of available product types that are available in the API'
    items:
      $ref: '#/components/schemas/ProductType'
example:
  type: 'list'
  url: '/product-types'
  data:
    - object: 'product-type'
      url: '/product-types/hydromechanical_grease_interceptor'
      name: 'Hydromechanical Grease Interceptor'
      key: 'hydromechanical_grease_interceptor'
      active: true
      created: '11/24/2020'
      last_updated: null
      parent: null
      types: []
    - object: 'product-type'
      url: '/product-types/gravity_grease_interceptor'
      name: 'Gravity Grease Interceptor'
      key: 'gravity_grease_interceptor'
      active: true
      created: '11/24/2020'
      last_updated: null
      parent: null
      types: []
    - object: 'product-type'
      url: '/product-types/accessory'
      name: 'Accessory'
      key: 'accessory'
      active: true
      created: '11/24/2020'
      last_updated: null
      parent: null
      types:
        - object: 'product-type'
          url: '/product-types/riser'
          name: 'Riser'
          key: 'riser'
          active: true
          created: '11/24/2020'
          last_updated: null
        - object: 'product-type'
          url: '/product-types/pumpout_port'
          name: 'Pumpout Port'
          key: 'pumpout_port'
          active: true
          created: '11/24/2020'
          last_updated: null