type: object
properties:
  object:
    type: string
    default: 'list'
  url:
    type: string
    description: 'The url that can be used to retrieve this product list.'
    example: '/products?variants=true&limit=1&offset=0'
  data:
    type: array
    description: 'A list of available products that are available in the API'
    items:
      $ref: '#/components/schemas/Product'