type: object
properties:
  object:
    type: string
    default: 'product-type'
  url:
    type: string
    description: 'The url that can be used to retrieve this product type.'
    example: '/product-types/hydromechanical_grease_interceptor'
  name:
    type: string
    description: 'The human-friendly name of the product type'
    example: 'Hydromechanical Grease Interceptor'
  key:
    type: string
    description: 'The slug/key of the product type. Usually a lower case, underscored version of the name.'
    example: 'hydromechanical_grease_interceptor'
  active:
    type: boolean
    description: 'The published-status of this product type (ie. should this type be shown on the eCommerce store.'
  image:
    type: string
    nullable: true
    description: 'If available, the image that can be used as a type of "cover image" to represent this product type.'
  created:
    type: string
    description: 'The date of when the product type was created.'
    example: '11/24/2020'
  last_updated:
    type: string
    nullable: true
    description: 'If available, the date of when the product type was updated.'
    example: '11/24/2020'
  parent:
    type: object
    nullable: true
    description: 'If the represented product type is a child product type, this object will represent the parent product type.'
  types:
    type: array
    description: 'If the current product type is a parent, these are the associated children product types'
    items:
      $ref: '#/components/schemas/ProductType'
