type: object
description: "A list of web-optimized images with assorted sizes and attributes to be used in both a marketing and specification manner.\n\n **primary:** The main, marketing image of the product.\n **dimension:** The image of the product with the dimension (length, width, etc) indicators to show scale."
example:
  object: 'product-image-library'
  primary:
    object: 'product-image'
    orig: 'https://dev-schier-api.nyc3.cdn.digitaloceanspaces.com/product-photos/gb-1000/de1d7644-1a8d-4f7e-9b39-58cd57b7c6ff.png'
    lg: 'https://dev-schier-api.nyc3.cdn.digitaloceanspaces.com/product-photos/gb-1000/de1d7644-1a8d-4f7e-9b39-58cd57b7c6ff_lg.png'
    md: 'https://dev-schier-api.nyc3.cdn.digitaloceanspaces.com/product-photos/gb-1000/de1d7644-1a8d-4f7e-9b39-58cd57b7c6ff_md.png'
    sm: 'https://dev-schier-api.nyc3.cdn.digitaloceanspaces.com/product-photos/gb-1000/de1d7644-1a8d-4f7e-9b39-58cd57b7c6ff_sm.png'
properties:
  object:
    type: string
    default: 'product-image-library'
  primary:
    $ref: "#/components/schemas/PhotoLibrary"
  dimension:
    $ref: "#/components/schemas/PhotoLibrary"