type: object
properties:
  object:
    type: string
    default: certification
  type:
    type: string
    enum:
      - link
      - file
    description: "The medium of the document that is provided.\n**link** – an externally hosted file that is simply linked to\n**file** – a self-hosted file that Schier owns"
  name:
    type: string
    description: A descriptive name to provide context to the document.
    example: GB-1000 ASME Test Report (200 GPM)
  link:
    type: string
    description: A link to the provided asset.
